language: python
python:
  - "3.3"
  - "2.7"
  - "3.4"
  - "2.6"

env:
  - DJANGO_VERSION=Django==1.4.10
  - DJANGO_VERSION=Django==1.5.5
  - DJANGO_VERSION=Django==1.6.2
  - DJANGO_VERSION=https://www.djangoproject.com/download/1.7a2/tarball/

install:
  - pip install -q $DJANGO_VERSION --use-mirrors
  - python setup.py install

script: make test

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.10
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.5.5  
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.10
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.5.5
    - python: "2.6"
      env: DJANGO_VERSION=https://www.djangoproject.com/download/1.7a2/tarball/

notifications:
  email: false
